"""
Surfcam prototype - Pi-side servo hold test (hardware PWM version).

Uses true hardware PWM via the SoC's dedicated PWM0/PWM1 peripheral
(through the rpi_hardware_pwm package's /sys/class/pwm wrapper), not
software-timed PWM. Both raw lgpio (tx_servo/tx_pwm - produced zero
output at all) and gpiozero's AngularServo (jittery - gpiozero's own
PWMSoftwareFallback warning confirms it falls back to a Python-timed PWM
loop for the Servo class unless pigpio is present) failed on this Pi.
pigpio itself isn't installable on Raspberry Pi OS Trixie. Hardware PWM
sidesteps all of this: pulses are generated by the SoC's PWM peripheral
itself, immune to Python/OS scheduling jitter.

Sends a servo between its mapped safe min/max angle (SAFE_RANGE below,
same table as servo_test.py) with a 2-second hold at each end.

One-time setup on the Pi (reboot required for the overlay to take effect):
    echo "dtoverlay=pwm-2chan" | sudo tee -a /boot/firmware/config.txt
    sudo reboot
    pip3 install rpi-hardware-pwm --break-system-packages

After the overlay is enabled, GPIO18 = PWM channel 0 (pan/MG90S),
GPIO19 = PWM channel 1 (tilt/SG90). Confirm with:
    cat /sys/class/pwm/pwmchip0/npwm   # should print 2

Run this ON the Raspberry Pi. May need sudo if you get a permissions
error writing to /sys/class/pwm.

Usage:
    python3 hold_test.py       # tests both pan (channel 0) and tilt (channel 1)
    python3 hold_test.py 0     # tests only the given PWM channel (0 or 1)
"""

import sys
import time

from rpi_hardware_pwm import HardwarePWM

PAN_CHANNEL = 0   # GPIO18
TILT_CHANNEL = 1  # GPIO19
FREQUENCY_HZ = 50
PERIOD_US = 1_000_000 / FREQUENCY_HZ  # 20000us at 50Hz

# Electrical full-scale range the pulse-width formula below is calibrated
# against (500-2500us spans this full +/-90 range) - NOT the same as a
# given servo's actual safe range, which comes from SAFE_RANGE below.
ELECTRICAL_MIN_ANGLE = -90
ELECTRICAL_MAX_ANGLE = 90
MIN_PULSE_US = 500
MAX_PULSE_US = 2500

# Per-servo safe range, mapped out with servo_test.py. Pan confirmed
# -80/+80 on 2026-07-20 after re-basing the rig so mechanical center
# lines up with 0 degrees. Tilt was remapped to -40/+10 on 2026-07-22
# after the original SG90 melted and was replaced - the new unit's
# mounted zero position differs from the old one, so the old -10/+60
# range no longer applies. Positive angle = tilt down, negative = tilt up
# (this is the original convention - a brief report on 2026-07-22 that it
# had flipped was itself mistaken, confirmed via actual auto-tracking runs).
SAFE_RANGE = {
    PAN_CHANNEL: (-80, 80),
    TILT_CHANNEL: (-40, 10),
}

HOLD_SECONDS = 2


def angle_to_duty_percent(angle):
    span = ELECTRICAL_MAX_ANGLE - ELECTRICAL_MIN_ANGLE
    pulse_us = MIN_PULSE_US + (angle - ELECTRICAL_MIN_ANGLE) / span * (MAX_PULSE_US - MIN_PULSE_US)
    return (pulse_us / PERIOD_US) * 100


def hold_test(channel, label):
    lo, hi = SAFE_RANGE[channel]
    pwm = HardwarePWM(pwm_channel=channel, hz=FREQUENCY_HZ, chip=0)
    pwm.start(angle_to_duty_percent(0))
    print(f"{label} (channel {channel}): moving to {lo} degrees")
    pwm.change_duty_cycle(angle_to_duty_percent(lo))
    time.sleep(HOLD_SECONDS)
    print(f"{label} (channel {channel}): moving to {hi} degrees")
    pwm.change_duty_cycle(angle_to_duty_percent(hi))
    time.sleep(HOLD_SECONDS)
    pwm.stop()
    print(f"{label} (channel {channel}): stopped")


def main():
    if len(sys.argv) > 1:
        channel = int(sys.argv[1])
        hold_test(channel, "servo")
    else:
        hold_test(PAN_CHANNEL, "pan")
        hold_test(TILT_CHANNEL, "tilt")


if __name__ == "__main__":
    main()
