"""
Surfcam prototype - Pi-side servo test (hardware PWM version).

Uses true hardware PWM via the SoC's dedicated PWM0/PWM1 peripheral
(through the rpi_hardware_pwm package) - see hold_test.py's docstring for
why software-timed PWM (raw lgpio, then gpiozero's AngularServo) didn't
work out on this Pi. Both servos are held simultaneously here: hardware
PWM is generated by the SoC peripheral itself, not vulnerable to CPU/
Python scheduling jitter, and holding both simultaneously also matches
how the real tracking system will eventually need both servos moving
together.

Purpose: verify wiring, confirm which direction each servo turns for a
given angle, and find the safe min/max range before the bracket binds or
a servo strains against a mechanical limit.

No webcam/CV involved - this is pure servo/GPIO validation, done before
wiring the webcam back in or writing the UDP receiver.

One-time setup on the Pi (reboot required for the overlay to take effect):
    echo "dtoverlay=pwm-2chan" | sudo tee -a /boot/firmware/config.txt
    sudo reboot
    pip3 install rpi-hardware-pwm --break-system-packages

After the overlay is enabled, GPIO18 = PWM channel 0 (pan/MG90S),
GPIO19 = PWM channel 1 (tilt/SG90). Confirm with:
    cat /sys/class/pwm/pwmchip0/npwm   # should print 2

Run this ON the Raspberry Pi. May need sudo if you get a permissions
error writing to /sys/class/pwm.

Controls:
    +       nudge the active servo's angle up by 10 degrees (clamped to
            its mapped safe range - see SAFE_RANGE below)
    -       nudge the active servo's angle down by 10 degrees (clamped)
    c       recenter the active servo (0 degrees)
    p       switch active servo to pan (channel 0 / GPIO18)
    t       switch active servo to tilt (channel 1 / GPIO19)
    q       quit (stops both channels so they don't hum/heat idle)

Nudge in small steps and watch/listen - back off immediately if a servo
strains, buzzes, or the bracket binds. Update SAFE_RANGE below once a
servo's real limits are known.
"""

from rpi_hardware_pwm import HardwarePWM

PAN_CHANNEL = 0   # GPIO18
TILT_CHANNEL = 1  # GPIO19
FREQUENCY_HZ = 50
PERIOD_US = 1_000_000 / FREQUENCY_HZ  # 20000us at 50Hz

# Electrical full-scale range the pulse-width formula below is calibrated
# against (500-2500us spans this full +/-90 range) - NOT the same as a
# given servo's actual safe range, which is enforced separately via
# SAFE_RANGE below.
ELECTRICAL_MIN_ANGLE = -90
ELECTRICAL_MAX_ANGLE = 90
MIN_PULSE_US = 500
MAX_PULSE_US = 2500

# Per-servo safe range, mapped out with this script. Pan confirmed
# -80/+80 on 2026-07-20 after re-basing the rig so mechanical center
# lines up with 0 degrees. Tilt was remapped to -40/+10 on 2026-07-22
# after the original SG90 melted and was replaced - the new unit's
# mounted zero position differs from the old one, so the old -10/+60
# range no longer applies. Positive angle = tilt down, negative = tilt up
# (this is the original convention - a brief report on 2026-07-22 that it
# had flipped was itself mistaken, confirmed via actual auto-tracking runs).
SAFE_RANGE = {
    PAN_CHANNEL: (-80, 80),
    TILT_CHANNEL: (-40, 10),
}

STEP_DEG = 10

# Default/recenter angle per servo. Tilt defaults to -30, not the
# mechanical calibration zero (0) - with the camera actually mounted, -30
# is what puts the camera roughly straight ahead in practice, confirmed
# empirically 2026-07-22. Within the -40/+10 safe range.
DEFAULT_ANGLE = {
    PAN_CHANNEL: 0,
    TILT_CHANNEL: -30,
}


def angle_to_duty_percent(angle):
    span = ELECTRICAL_MAX_ANGLE - ELECTRICAL_MIN_ANGLE
    pulse_us = MIN_PULSE_US + (angle - ELECTRICAL_MIN_ANGLE) / span * (MAX_PULSE_US - MIN_PULSE_US)
    return (pulse_us / PERIOD_US) * 100


def main():
    pwms = {
        PAN_CHANNEL: HardwarePWM(pwm_channel=PAN_CHANNEL, hz=FREQUENCY_HZ, chip=0),
        TILT_CHANNEL: HardwarePWM(pwm_channel=TILT_CHANNEL, hz=FREQUENCY_HZ, chip=0),
    }
    names = {PAN_CHANNEL: "pan (GPIO18)", TILT_CHANNEL: "tilt (GPIO19)"}
    angle = {PAN_CHANNEL: DEFAULT_ANGLE[PAN_CHANNEL], TILT_CHANNEL: DEFAULT_ANGLE[TILT_CHANNEL]}
    active_channel = PAN_CHANNEL

    for channel, pwm in pwms.items():
        pwm.start(angle_to_duty_percent(DEFAULT_ANGLE[channel]))
    print(f"Pan at {DEFAULT_ANGLE[PAN_CHANNEL]} degrees, tilt at {DEFAULT_ANGLE[TILT_CHANNEL]} "
          f"degrees (camera roughly level).")
    print("Controls: + / - nudge 10deg, c recenter, p=pan, t=tilt, q=quit\n")

    try:
        while True:
            lo, hi = SAFE_RANGE[active_channel]
            print(f"[{names[active_channel]}] angle={angle[active_channel]}deg "
                  f"(safe range {lo} to {hi})  > ", end="")
            cmd = input().strip().lower()

            if cmd == "q":
                break
            elif cmd == "p":
                active_channel = PAN_CHANNEL
            elif cmd == "t":
                active_channel = TILT_CHANNEL
            elif cmd == "c":
                angle[active_channel] = DEFAULT_ANGLE[active_channel]
                pwms[active_channel].change_duty_cycle(
                    angle_to_duty_percent(DEFAULT_ANGLE[active_channel]))
            elif cmd == "+":
                lo, hi = SAFE_RANGE[active_channel]
                angle[active_channel] = min(hi, angle[active_channel] + STEP_DEG)
                pwms[active_channel].change_duty_cycle(angle_to_duty_percent(angle[active_channel]))
            elif cmd == "-":
                lo, hi = SAFE_RANGE[active_channel]
                angle[active_channel] = max(lo, angle[active_channel] - STEP_DEG)
                pwms[active_channel].change_duty_cycle(angle_to_duty_percent(angle[active_channel]))
            else:
                print("unrecognized command (use +, -, c, p, t, or q)")
    finally:
        for pwm in pwms.values():
            pwm.stop()
        print("Stopped both channels.")


if __name__ == "__main__":
    main()
